[package]
name = "wv-sys"
version = "0.1.2"
edition = "2021"
description = "Webview raw ffi bindings"
repository = "https://github.com/MoAlyousef/wv"
documentation = "https://docs.rs/wv-sys"
categories = ["gui"]
readme = "README.md"
license = "MIT"

[build-dependencies]
pkg-config = "0.3"
cc = "1"